version: 2
snapshot:
  widths:
    - 500  
  minHeight: 500
  percyCSS: |
    .percy-only-css-global {
      background-color: #1B1F3A;
      margin: 40px;
    }
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 100
upload:
  files: '**/*.{png,jpg,jpeg}'
  ignore: ''
  stripExtensions: false