export const baseTheme = {
  colors: {
    darkenPrimary: '#E0630F',
    primary: '#f0690f',
    lightenPrimary: '#fc802d',
    darkenSecondary: '#91403A',
    secondary: '#A64942',
    lightenSecondary: '#C35850',
    backgroundSecondary: '#53354A',
    disabled: '#999593',
  },
  typography: {
    h1: {
      fontFamily: 'Kdam Thmor Pro, Franklin Gothic Medium, Arial Narrow, Arial,sans-serif',
      fontSize: 50,
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: 'normal',
      letterSpacing: 1,
    },
    h2: {
      fontFamily: 'Kdam Thmor Pro, Franklin Gothic Medium, Arial Narrow, Arial,sans-serif',
      fontSize: 40,
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: 'normal',
      letterSpacing: 1,
    },
    body1: {
      fontFamily: 'Arial, sans-serif',
      fontSize: 18,
      fontStyle: 'normal',
      fontWeight: 400,
      lineHeight: 'normal',
      letterSpacing: 1,
    },
    body2: {
      fontFamily: 'Arial, sans-serif',
      fontSize: 16,
      fontStyle: 'normal',
      fontWeight: 400,
      lineHeight: 'normal',
      letterSpacing: 1,
    },
    button: {
      fontFamily: 'Source Code Pro, Arial',
      fontSize: 16,
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: 'normal',
      letterSpacing: 1,
    },
    label: {
      fontFamily: 'Source Code Pro, Arial',
      fontSize: 14,
      fontStyle: 'normal',
      fontWeight: 200,
      lineHeight: 'normal',
      letterSpacing: 1,
    },
  },
};
